CREATE TABLE HomeWork (Id INTEGER PRIMARY KEY AUTOINCREMENT,
Title text,
DateOfReadyness INTEGER);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE UserHomeWork (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Checked INTEGER NOT NULL CHECK(Checked IN (0,1)),
UserId INTEGER NOT NULL,
HomeWorkId INTEGER NOT NULL,
FOREIGN KEY(HomeWorkId) REFERENCES HomeWork(Id),
FOREIGN KEY(UserId) REFERENCES User(Id));
CREATE TABLE UserHomeWorkReminder(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
UserId INTEGER NOT NULL,
HomeWorkId INTEGER NOT NULL,
IsSend INTEGER NOT NULL CHECK(IsSend IN (0,1)),
DateTimeSend INTEGER NOT NULL,
FOREIGN KEY(UserId) REFERENCES User(Id),
FOREIGN KEY(HomeWorkId) REFERENCES HomeWork(Id));
CREATE TABLE Action(
Id INTEGER PRIMARY KEY NOT NULL,
Name TEXT NOT NULL,
Description TEXT);
CREATE TABLE ActionUserSend(
Id INTEGER PRIMARY KEY NOT NULL,
ActionId INTEGER NOT NULL,
UserId INTEGER NOT NULL,
FOREIGN KEY(UserId) REFERENCES User(Id),
FOREIGN KEY(ActionId) REFERENCES Action(Id));
CREATE TABLE HomeWorkUserSend(
Id INTEGER PRIMARY KEY NOT NULL,
HomeWorkId INTEGER NOT NULL,
UserId INTEGER NOT NULL,
IsSend INTEGER NOT NULL CHECK(IsSend IN (0,1)),
FOREIGN KEY(HomeWorkId) REFERENCES HomeWork(Id),
FOREIGN KEY(UserId) REFERENCES User(Id));
CREATE TABLE user (Id integer primary key autoincrement, Name text, Surname text, ChatId text not null);
